logging:
  level:
    root: info
    com:
      dnslin:
        onemanager:
    com.dnslin.pay: debug

pay:
  alipay:
    appId: "*******"
    privateKey: "*******************"
    alipayPublicKey: "******"
    notifyUrl: "https://baidu.com"
    serverUrl: "https://openapi.alipay.com/gateway.do"


server:
  port: 6789